---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/thanos --version
      register: thanos_test_output
    - debug:
        msg: '{{ thanos_test_output.stderr }}'
